export const JWT_AUTH_SECRET = process.env.JWT_AUTH_SECRET || 'AUTH_SECRET'
export const JWT_AUTH_REFRESH_SECRET = process.env.JWT_AUTH_REFRESH_SECRET || 'AUTH_REFRESH_SECRET'
export const JWT_ADMINAUTH_SECRET = process.env.JWT_ADMINAUTH_SECRET || 'ADMINAUTH_SECRET'
export const JWT_ADMINAUTH_REFRESH_SECRET = process.env.JWT_ADMINAUTH_REFRESH_SECRET || 'ADMINAUTH_REFRESH_SECRET'

export const JWT_SOCKET_SECRET = process.env.JWT_SOCKET_SECRET || 'SOCKET_SECRET'

export const JWT_GAPPS_SECRET = process.env.JWT_GAPPS_SECRET || 'GAPPS_SECRET'
